# Generated by Django 4.0 on 2024-03-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissiere',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caissiere_user', to='Agence.user'),
        ),
        migrations.AlterField(
            model_name='gerant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gerant_user', to='Agence.user'),
        ),
        migrations.AlterField(
            model_name='touriste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touriste_user', to='Agence.user'),
        ),
    ]
